INHERIT: ./mkdocs.base.yml

site_name: TACC HPC Documentation
site_description: TACC Technical Documentation
site_author: Susan Lindsey
site_url: https://docs.tacc.utexas.edu
# To suppport "Edit on Github" link
# SEE: https://www.mkdocs.org/user-guide/configuration/#repo_name
# repo_url: https://github.com/TACC/TACC-Docs
# edit_uri: edit/main/docs/

theme:
    analytics:
        gtag: G-TRRRQZ0EHX
    cms_url: https://tacc.utexas.edu # TACC Feature
    cms_name: tacc.utexas.edu # TACC Feature
    # nav_name: Documentation # TACC Feature

nav:
  - TACC Essentials:
    - Documentation Overview: index.md
    - Getting Started: https://www.tacc.utexas.edu/use-tacc/getting-started/
    - Portal Access: portal.md
    - Multi-Factor Authentication: basics/mfa.md
    - TACC Good Conduct Guide: basics/conduct.md
    - Data Transfer Guide: basics/datatransfer.md
    - Software at TACC: basics/software.md
    - Help: basics/help.md
  - HPC User Guides:
    - Chameleon: https://chameleoncloud.readthedocs.io/en/latest
    - Corral: hpc/corral.md
    - Frontera: hpc/frontera.md
    - Lonestar6: hpc/lonestar6.md
    - Jetstream2: https://docs.jetstream-cloud.org
    - Ranch: hpc/ranch.md
    - Stampede3: hpc/stampede3.md
    - Stallion: hpc/stallion.md
    - Vista: hpc/vista.md
  - Software Packages:
    - ABAQUS: software/abaqus.md
    - AlphaFold : software/alphafold.md
    - ANSYS: software/ansys.md
    - CD Tools: software/cdtools.md
    - Gaussian: software/gaussian.md
    - GROMACS: software/gromacs.md
    - idev: software/idev.md
    - LAMMPS: software/lammps.md
#    - Launcher: software/launcher.md
    - Lmod: https://lmod.readthedocs.io/en/latest
    - MATLAB: software/matlab.md
    - NAMD: software/namd.md
    - OpenFOAM: software/openfoam.md
    - ParaView: software/paraview.md
    - PyLauncher: software/pylauncher.md
    - Quantum Espresso: software/quantumespresso.md 
    - REMORA: software/remora.md
    - TAU: software/tau.md
#    - Tensorflow: software/tensorflow.md
    - VASP: software/vasp.md
    - VisIt: software/visit.md
  - TACC Tutorials:
    - Access Control Lists: tutorials/acls.md
    - Bash Quick Start Guide: tutorials/bashstartup.md
    - BLAS/LAPACK: tutorials/blas-lapack.md
    - Containers at TACC: https://containers-at-tacc.readthedocs.io/en/latest/index.html
    - DDT Debugger: tutorials/ddt.md
    - Managing Group Permissions: tutorials/permissions.md
    - Managing I/O: tutorials/managingio.md
    - MAP: tutorials/map.md
    - Remote Desktop Access: tutorials/remotedesktopaccess.md
    - Sharing Project Files: tutorials/sharingprojectfiles.md
    - TACC Analysis Portal: tutorials/TAP.md
#  - Fiddling:
#    - Testing Extensions: testingextensions.md
#    - Code Examples: code-examples/index.md

plugins:
  - search
  - exclude-search:
      exclude:
        - aliases.md
        - include/*
        - index-sample/*
        - code-examples/*
        - testingextensions.md
        - archives/*
  - macros # allows {% include ... %} (and macros)
# TODO: Restore this
#  - with-pdf:
#      copyright: TACC
#      cover_subtitle: TACC User Guide
#      toc_title: TACC User Guide
#      output_path: docs/user-guide.pdf
