site_name: TACC HPC Documentation
site_description: TACC Technical Documentation
site_author: Susan Lindsey
site_url: https://docs.tacc.utexas.edu
cms_url: https://dev.tup.tacc.utexas.edu # TACC Feature
cms_name: tacc.utexas.edu # TACC Feature
repo_url: https://github.com/TACC/TACC-Docs
edit_uri: edit/main/docs/

theme:
    name: readthedocs
    logo: /img/tacc-logo-with-words.svg
    collapse_navigation: false
    highlightjs: true
    hljs_languages:
        - bash
        - ruby
        - plaintext
        # for examples
        - shell
        - nginx
        - apache
        - xml
        - applescript
    hljs_aliases: # TACC Feature
        - name: cmd-line
          lang: ruby
        - name: job-script
          lang: bash
        - name: syntax
          lang: plaintext
    custom_dir: themes/readthedocs

extra_css:
    - css/bootstrap.css
    - css/core-styles.css
    - css/tacc-docs.css

# These must be modules
# SEE: /themes/readthedocs/main.html @ "block scripts"
extra_javascript:
    - js/modules/setTargetForExternalLinks.js
    - js/modules/styleLinksOutsideMainContent.js
    - js/modules/swapImgSvgWithRawSvg.js
    - js/modules/removeThemeClasses.js
    - js/modules/addNavClasses.js

nav:
  - TACC Basics :
    - Getting Started: basics/gettingstarted.md
    - New User Information: basics/newuserinfo.md
    - Data Transfer Guide: basics/datatransferguide.md
    - Good Conduct on HPC Resources: basics/conduct.md
    - Help: basics/help.md
  - HPC :
    - Chameleon: https://chameleoncloud.readthedocs.io/en/latest
    - Corral: hpc/corral.md
    - Frontera: hpc/frontera.md
    - Lonestar6: hpc/lonestar6.md
    - Jetstream2: https://docs.jetstream-cloud.org
    - Maverick2: hpc/maverick2.md
    - Ranch: hpc/ranch.md
    - Stampede2: hpc/stampede2.md
    - Stallion: hpc/stallion.md
  - Software :
    - ABAQUS: software/abaqus.md
    - AlphaFold : software/alphafold.md
    - ANSYS: software/ansys.md
    - CD Tools: software/cdtools.md
    - Gaussian: software/gaussian.md
    - GROMACS: software/gromacs.md
    - idev: software/idev.md
    - IRODS: software/irods.md
    - LAMMPS: software/lammps.md
    - Launcher: software/launcher.md
    - Lmod: https://lmod.readthedocs.io/en/latest
    - MATLAB: software/matlab.md
    - NAMD: software/namd.md
    - OpenFOAM: software/openfoam.md
    - Paraview VisIt: software/paraview-visit.md
    - Quantum Espresso: software/quantumespresso.md 
    - REMORA: software/remora.md
    - TAU: software/tau.md
    - Tensorflow: software/tensorflow.md
    - VASP: software/vasp.md
  - Tutorials :
    - Access Control Lists: tutorials/acls.md
    - Bash Quick Start Guide: tutorials/bashstartup.md
    - BLAS/LAPACK: tutorials/blas-lapack.md
    - DDT Debugger: tutorials/ddt.md
    - Grid Community Toolkit: tutorials/gridcommunitytoolkit.md
    - Managing I/O: tutorials/managingio.md
    - MAP: tutorials/map.md
    - Multi-Factor Authentication: tutorials/mfa.md
    - Remote Desktop Access: tutorials/remotedesktopaccess.md
    - Sharing Project Files: tutorials/sharingprojectfiles.md
    - TACC Analysis Portal: tutorials/TAP.md
  - Fiddling :
    - Sample Index Pages:
      - Sample 1: index-sample/sample-1.md
      - Sample 2: index-sample/sample-2.md
    - Testing Extensions: testingextensions.md
    - Code Examples: code-examples/index.md


# Python-Markdown extensions
# https://python-markdown.github.io/extensions/
markdown_extensions:
  - footnotes
  - def_list
  - admonition
  - attr_list
  - abbr
  # Enabled by MkDocs by default
  # https://github.com/mkdocs/mkdocs/blob/1.4.2/docs/user-guide/configuration.md#markdown_extensions
  # - meta
  # - toc
  # - tables
  # - fenced_code
  # Extensions from PyMdown
  # https://facelessuser.github.io/pymdown-extensions
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.saneheaders
  - pymdownx.details
  - pymdownx.blocks.tab
    # There is an alternative style that supports experimental mobile UX
    # SEE: https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/#alternate-style
  - pymdownx.blocks.html
  # FAQ: The `pymdownx.highlight` is useful only if Pygments is installed
  #      because Pygments would offer:
  #      - build-time syntax highlight markup
  #      - custom language tags and formatters
  # WARNING: Installing Pygments causes MkDocs build error
  # - pymdownx.highlight
  #     use_pygments: true

plugins:
  - search
  - macros # allows {% include ... %} (and macros)
#  - with-pdf:
#      copyright: TACC
#      cover_subtitle: TACC User Guide
#      toc_title: TACC User Guide
#      output_path: docs/user-guide.pdf
